version: '3'

services:
  db:
    image: postgres
    environment:
     POSTGRES_PASSWORD: mysecretpassword
     PGDATA: /var/lib/postgresql/data/pgdata
     POSTGRES_DB: module_7_drf

  online_school:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - '8000:8000'
    depends_on:
     - db
